[theme]
primaryColor = "#6366f1"
backgroundColor = "#0c0b13"
secondaryBackgroundColor = "#1a162b"
textColor = "#f3f4f6"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = true
port = 8502

